### ISSUE TITLE
Cannot read property 'onDidEndTour' of undefined

### ISSUE THREAD

**Issue by ctf0** [vsls-contrib/gistpad#194]
an error keep showing up in console
```
rejected promise not handled within 1 second: TypeError: Cannot read property 'onDidEndTour' of undefined
extensionHostProcess.js:1089
stack trace: TypeError: Cannot read property 'onDidEndTour' of undefined
    at Object.onDidEndTour (/Users/koka/.vscode-insiders/extensions/vsls-contrib.gistfs-0.1.10/out/prod/extension.js:31:144856)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Desktop (please complete the following information):**
 - VS Code Version [1.52.0-insider]
 - GistPad Version [e.g. v0.1.10]

**Comment by lostintangent** [comment]
Just pushed a fix for this, and I'm deploying an update to the marketplace right now. Thanks!
